---
title: "Casos Activos La Florida"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CASOS ACTIVOS PARA COMUNA DE LA FLORIDA

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.


```{r}
library(tidyverse)
library(highcharter)

```


```{r}
Activos <- read_csv("https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto19/CasosActivosPorComuna.csv")

Activos <- Activos %>% pivot_longer(starts_with("2022"), names_to = "Fecha", values_to = "Infectados") %>% 
  mutate(Fecha = lubridate::ymd(Fecha)) %>% 
  dplyr::filter(Comuna != "Total") %>% 
  mutate(Infectados_por_100.000 = (Infectados/Poblacion)*100000) %>% 
  dplyr::filter(Region %in% c("Metropolitana"))

Activos_LaFlorida <- Activos %>% dplyr::filter(Comuna=='La Florida')

hchart(Activos_LaFlorida,"line",hcaes(Fecha,Infectados)) %>%  hc_title(text = "Activos La Florida") %>% hc_add_theme(hc_theme_google())

```

